
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-s
  labels: 
    app: c-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c-s
  template:
    metadata:
      labels:
        app: c-s
    spec:
      containers:
      - name: c-s-app
        image: {{ .Values.image.server.repository }}
        env:
        - name: CLIENT_ADDRESS
          value: "http://c-c-service:80"
        ports:
        - name: c-s-port
          containerPort: 4000
      
